### ISSUE TITLE
  Cannot access protected property Lightship\Report::$durationInSeconds

### ISSUE THREAD

**Issue by Spir** [lightship-core/lightship-laravel#8]
When using _php artisan lightship:run --url example.com_ I get error:

  Cannot access protected property Lightship\Report::$durationInSeconds

  at vendor/lightship-core/lightship-laravel/src/Commands/LightshipRun.php:168

That var appear to be public: https://raw.githubusercontent.com/lightship-core/lightship-php/master/src/Report.php on last version but not on the 0.5.0 that has been installed.

using PHP 8.1.3

**Comment by khalyomede** [comment]
Hi, glad this package peaked your curiosity 😎

Could you please uninstall/reinstall it? I've made a breaking change to the underlying lightship-core/lightship-php package, this explains why you have not the update right now.

Let me know if this works for you!

**Comment by Spir** [comment]
Hi,
I still have the problem. The install loaded those versions:
lightship-core/lightship-laravel (0.3.1)
lightship-core/lightship-php (0.5.0)

**Comment by khalyomede** [comment]
Alright then let's try to force-update the package and its dependencies:

```bash
composer update lightship-core/lightship-laravel --with-all-dependencies
```

Let me know if this one solves your issue

**Comment by Spir** [comment]
fixed. thanks

**Comment by khalyomede** [comment]
Great to read! Sorry for this inconvenience
